"""Diff acquisition, filtering, and lightweight parsing."""

import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

from ai_security_review.constants import (
    MAX_CONTEXT_FILE_CHARS,
    MAX_CONTEXT_TOTAL_CHARS,
    MAX_DIFF_CHARS,
)
from ai_security_review.logger import get_logger

logger = get_logger(__name__)

GENERATED_MARKERS = (
    "@generated",
    "Code generated by OpenAPI Generator",
    "Code generated by protoc-gen-go",
    "DO NOT EDIT",
)

# Files that are never worth a security scan on their own.
SKIPPED_SUFFIXES = (".lock", ".min.js", ".min.css", ".map", ".snap", ".svg", ".png", ".jpg", ".jpeg", ".gif", ".ico", ".woff", ".woff2", ".ttf")
SKIPPED_BASENAMES = ("package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock", "Cargo.lock", "go.sum", "Gemfile.lock", "composer.lock")


@dataclass
class DiffFile:
    """One file section of a unified diff."""

    path: str
    status: str            # added | modified | deleted | renamed
    old_path: Optional[str]
    patch: str
    additions: int = 0
    deletions: int = 0
    added_lines: List[int] = field(default_factory=list)  # new-side line numbers that were added


@dataclass
class DiffBundle:
    """A filtered diff plus the parsed per-file view of it."""

    text: str
    files: List[DiffFile]
    excluded: List[str] = field(default_factory=list)
    truncated: bool = False

    @property
    def paths(self) -> List[str]:
        return [f.path for f in self.files]

    def is_empty(self) -> bool:
        return not self.files


class ExclusionRules:
    """Directory / file exclusion shared by diff filtering and finding filtering."""

    def __init__(self, exclude_dirs: Optional[List[str]] = None):
        self.exclude_dirs = [d.strip().strip("/").removeprefix("./") for d in (exclude_dirs or []) if d and d.strip()]

    def is_excluded(self, path: str) -> bool:
        if not path:
            return False
        normalized = path.removeprefix("./")
        base = normalized.rsplit("/", 1)[-1]
        if base in SKIPPED_BASENAMES or normalized.endswith(SKIPPED_SUFFIXES):
            return True
        parts = normalized.split("/")
        for excluded in self.exclude_dirs:
            excluded_parts = excluded.split("/")
            n = len(excluded_parts)
            for i in range(len(parts) - n):
                if parts[i : i + n] == excluded_parts:
                    return True
        return False


_DIFF_HEADER = re.compile(r"^diff --git a/(?P<old>.+?) b/(?P<new>.+?)$", re.MULTILINE)
_HUNK_HEADER = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@")


def split_diff_sections(diff_text: str) -> List[str]:
    sections = re.split(r"(?=^diff --git )", diff_text, flags=re.MULTILINE)
    return [s for s in sections if s.strip()]


def parse_section(section: str) -> Optional[DiffFile]:
    header = _DIFF_HEADER.search(section)
    if not header:
        return None
    old_path, new_path = header.group("old"), header.group("new")
    status = "modified"
    if re.search(r"^new file mode", section, re.MULTILINE):
        status = "added"
    elif re.search(r"^deleted file mode", section, re.MULTILINE):
        status = "deleted"
    elif old_path != new_path or re.search(r"^rename from", section, re.MULTILINE):
        status = "renamed"

    additions = deletions = 0
    added_lines: List[int] = []
    new_line = 0
    in_hunk = False
    for line in section.splitlines():
        hunk = _HUNK_HEADER.match(line)
        if hunk:
            new_line = int(hunk.group(3))
            in_hunk = True
            continue
        if not in_hunk:
            continue
        if line.startswith("+++") or line.startswith("---"):
            continue
        if line.startswith("+"):
            additions += 1
            added_lines.append(new_line)
            new_line += 1
        elif line.startswith("-"):
            deletions += 1
        elif line.startswith("\\"):
            continue
        else:
            new_line += 1

    return DiffFile(
        path=new_path if status != "deleted" else old_path,
        status=status,
        old_path=old_path if old_path != new_path else None,
        patch=section,
        additions=additions,
        deletions=deletions,
        added_lines=added_lines,
    )


def _is_generated(section: str) -> bool:
    head = section[:4000]
    return any(marker in head for marker in GENERATED_MARKERS)


def build_bundle(diff_text: str, rules: Optional[ExclusionRules] = None, max_chars: int = MAX_DIFF_CHARS) -> DiffBundle:
    """Filter a raw unified diff and parse it into a :class:`DiffBundle`."""
    rules = rules or ExclusionRules()
    kept_sections: List[str] = []
    files: List[DiffFile] = []
    excluded: List[str] = []

    for section in split_diff_sections(diff_text or ""):
        parsed = parse_section(section)
        if parsed is None:
            continue
        if rules.is_excluded(parsed.path) or (parsed.old_path and rules.is_excluded(parsed.old_path)):
            excluded.append(parsed.path)
            continue
        if _is_generated(section):
            excluded.append(parsed.path)
            continue
        files.append(parsed)
        kept_sections.append(section)

    text = "".join(kept_sections)
    truncated = False
    if len(text) > max_chars and files:
        # Trim the largest sections first so small, interesting files survive intact.
        budget_per_file = max(2000, max_chars // len(files))
        trimmed = []
        for f in files:
            patch = f.patch
            if len(patch) > budget_per_file:
                patch = patch[:budget_per_file] + "\n... [patch truncated for size] ...\n"
                truncated = True
            trimmed.append(patch)
        text = "".join(trimmed)
    if excluded:
        logger.info("Excluded %d file(s) from the diff: %s", len(excluded), ", ".join(excluded[:10]))
    return DiffBundle(text=text, files=files, excluded=excluded, truncated=truncated)


def git_diff(repo_dir: Path, base: str, head: str = "HEAD", merge_base: bool = True) -> str:
    """Return the unified diff between ``base`` and ``head`` in ``repo_dir``."""
    args = ["git", "-C", str(repo_dir), "diff", "--no-color", "--no-ext-diff"]
    args.append(f"{base}...{head}" if merge_base else f"{base}..{head}")
    result = subprocess.run(args, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(f"git diff failed: {result.stderr.strip()}")
    return result.stdout


def git_working_tree_diff(repo_dir: Path, base: Optional[str] = None) -> str:
    """Diff of everything pending on the working tree (staged + unstaged) against ``base`` or HEAD."""
    args = ["git", "-C", str(repo_dir), "diff", "--no-color", "--no-ext-diff"]
    if base:
        args.append(base)
    result = subprocess.run(args, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(f"git diff failed: {result.stderr.strip()}")
    return result.stdout


def collect_context_files(repo_dir: Path, bundle: DiffBundle) -> Dict[str, str]:
    """Read the post-change contents of touched files, bounded by size, for the API backend."""
    contents: Dict[str, str] = {}
    total = 0
    for f in bundle.files:
        if f.status == "deleted":
            continue
        candidate = repo_dir / f.path
        try:
            if not candidate.is_file():
                continue
            raw = candidate.read_bytes()
        except OSError:
            continue
        if b"\0" in raw[:8000]:
            continue  # binary
        text = raw.decode("utf-8", errors="replace")
        if len(text) > MAX_CONTEXT_FILE_CHARS:
            text = text[:MAX_CONTEXT_FILE_CHARS] + "\n... [file truncated for size] ...\n"
        if total + len(text) > MAX_CONTEXT_TOTAL_CHARS:
            break
        contents[f.path] = text
        total += len(text)
    return contents
