import json
from pathlib import Path
from typing import Any, Dict, List

import pytest

from ai_security_review.claude_client import StructuredResponse
from ai_security_review.diff import build_bundle

SAMPLE_DIFF = """diff --git a/app/api/users.py b/app/api/users.py
index 1111111..2222222 100644
--- a/app/api/users.py
+++ b/app/api/users.py
@@ -10,6 +10,13 @@ from app.db import db
 
 router = APIRouter()
 
+@router.get("/users/{user_id}/export")
+def export_user(user_id: str, q: str = ""):
+    rows = db.execute(f"SELECT * FROM users WHERE id = '{user_id}' AND name LIKE '%{q}%'")
+    logger.info("export for %s with token %s", user_id, request.headers.get("Authorization"))
+    return rows
+
+
 @router.get("/users/{user_id}")
 def get_user(user_id: str):
     return db.get(user_id)
diff --git a/README.md b/README.md
index 3333333..4444444 100644
--- a/README.md
+++ b/README.md
@@ -1,2 +1,3 @@
 # App
+Added export endpoint.
diff --git a/vendor/lib.js b/vendor/lib.js
index 5555555..6666666 100644
--- a/vendor/lib.js
+++ b/vendor/lib.js
@@ -1 +1,2 @@
 // vendored
+eval(location.hash)
diff --git a/gen/api.pb.go b/gen/api.pb.go
index 7777777..8888888 100644
--- a/gen/api.pb.go
+++ b/gen/api.pb.go
@@ -1,2 +1,3 @@
 // Code generated by protoc-gen-go. DO NOT EDIT.
+var x = 1
"""


@pytest.fixture(autouse=True)
def no_external_tools(request, monkeypatch):
    """Keep gitleaks/semgrep binaries on the developer's machine out of the CLI tests.

    PipelineConfig runs no scanners unless asked, so only the CLI default needs pinning. Tests that
    exercise the scanner integration opt in with ``@pytest.mark.external_tools``.
    """
    if "external_tools" in request.keywords:
        return
    monkeypatch.setattr("ai_security_review.cli.DEFAULT_TOOLS", ())


@pytest.fixture
def sample_diff() -> str:
    return SAMPLE_DIFF


@pytest.fixture
def bundle():
    return build_bundle(SAMPLE_DIFF)


class FakeClaudeClient:
    """Stands in for ClaudeClient; returns canned structured responses keyed by label prefix."""

    def __init__(self, responses: Dict[str, Any], fail_labels: List[str] = None):
        self.responses = responses
        self.fail_labels = fail_labels or []
        self.calls: List[Dict[str, Any]] = []
        self.total_input_tokens = 0
        self.total_output_tokens = 0

    def structured_call(self, *, model, system, user, schema, max_tokens, effort="high", label="call"):
        from ai_security_review.claude_client import ClaudeCallError

        self.calls.append({"model": model, "system": system, "user": user, "schema": schema, "label": label, "effort": effort})
        if label in self.fail_labels:
            raise ClaudeCallError(f"{label}: simulated failure")
        key = label if label in self.responses else label.split(":")[0]
        data = self.responses[key]
        self.total_input_tokens += 100
        self.total_output_tokens += 50
        return StructuredResponse(data=data, model=model, input_tokens=100, output_tokens=50, request_id="req_test", raw_text=json.dumps(data))


@pytest.fixture
def fake_client_factory():
    return FakeClaudeClient


def triage_payload(data=True, exposure=True, access=False, conf=(0.9, 0.8, 0.3)):
    return {
        "summary": "Adds an export endpoint that builds SQL from the path and logs the auth header.",
        "change_kind": "feature",
        "risk_level": "high",
        "scans": {
            "data": {"relevant": data, "confidence": conf[0], "reason": "SQL built via f-string", "focus": ["app/api/users.py: export_user query"]},
            "exposure": {"relevant": exposure, "confidence": conf[1], "reason": "Authorization header logged", "focus": ["app/api/users.py: logger.info"]},
            "access": {"relevant": access, "confidence": conf[2], "reason": "No new auth logic", "focus": []},
        },
        "notes": "FastAPI app.",
    }


def scan_payload(findings, candidate_verdicts=None):
    return {"findings": findings, "candidate_verdicts": candidate_verdicts or [], "reviewed_files": ["app/api/users.py"], "notes": "checked"}


def finding(**overrides):
    base = {
        "file": "app/api/users.py",
        "line": 15,
        "severity": "HIGH",
        "category": "sql_injection",
        "title": "SQL injection in export_user",
        "description": "user_id and q are interpolated into the SQL string.",
        "exploit_scenario": "Attacker sets q to ' OR 1=1 -- to dump all rows.",
        "recommendation": "Use parameterised queries.",
        "confidence": 0.95,
        "introduced_by_change": True,
    }
    base.update(overrides)
    return base


@pytest.fixture
def helpers():
    return {"triage_payload": triage_payload, "scan_payload": scan_payload, "finding": finding}
